version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      # Only run create_tables.sql at initialization
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql

  data-loader:
    build: ./data-loader
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./sql:/app/sql
